---
version: '3.4'
services:

  bootnode:
    build:
      context: besu/.
      args:
        BESU_VERSION: ${BESU_VERSION}
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    entrypoint: /opt/besu/bootnode_start.sh
    command: &base_options [
      "--config-file=/config/config.toml",
      "--genesis-file=/config/genesis.json",
      "--node-private-key-file=/opt/besu/keys/key",
      "--min-gas-price=0",
      "--rpc-http-api=WEB3,ETH,NET,IBFT,ADMIN,PERM",
      "--rpc-ws-api=WEB3,ETH,NET,IBFT,ADMIN,PERM",
      "--permissions-accounts-contract-enabled=${PERMISSIONING_ENABLED}",
      "--permissions-accounts-contract-address=0x0000000000000000000000000000000000008888",
      "--permissions-nodes-contract-enabled=${PERMISSIONING_ENABLED}",
      "--permissions-nodes-contract-address=0x0000000000000000000000000000000000009999",
    ]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/ibft2GenesisPermissioning.json:/config/genesis.json
      - ./config/besu/networkFiles/bootnode/keys:/opt/besu/keys
      - bootnode:/opt/besu/data
    networks:
      sample:
        ipv4_address: 172.24.2.5

  validator2:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: *base_options
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/ibft2GenesisPermissioning.json:/config/genesis.json
      - ./config/besu/networkFiles/validator2/keys:/opt/besu/keys
      - validator2:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      sample:
        ipv4_address: 172.24.2.6

  validator3:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: *base_options
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/ibft2GenesisPermissioning.json:/config/genesis.json
      - ./config/besu/networkFiles/validator3/keys:/opt/besu/keys
      - validator3:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      sample:
        ipv4_address: 172.24.2.7

  validator4:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: *base_options
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/ibft2GenesisPermissioning.json:/config/genesis.json
      - ./config/besu/networkFiles/validator4/keys:/opt/besu/keys
      - validator4:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      sample:
        ipv4_address: 172.24.2.8

  rpcnode: #  We keep one node named rpcnode to have a specific node to connect the explorer
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: *base_options
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/ibft2GenesisPermissioning.json:/config/genesis.json
      - ./config/besu/networkFiles/rpcnode/keys:/opt/besu/keys
      - rpcnode:/opt/besu/data
    depends_on:
      - bootnode
    ports:
      - 8545:8545/tcp
    networks:
      sample:
        ipv4_address: 172.24.2.9

  node1:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: *base_options
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/ibft2GenesisPermissioning.json:/config/genesis.json
      - ./config/besu/networkFiles/node1/keys:/opt/besu/keys
      - node1:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      sample:
        ipv4_address: 172.24.2.11

  node2:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: *base_options
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/ibft2GenesisPermissioning.json:/config/genesis.json
      - ./config/besu/networkFiles/node2/keys:/opt/besu/keys
      - node2:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      sample:
        ipv4_address: 172.24.2.12

  explorer:
    build: block-explorer-light/.
    image: sample-network/block-explorer-light:${BESU_VERSION}
    depends_on:
      - rpcnode
    ports:
      - 25000:80/tcp
    networks:
      sample:
        ipv4_address: 172.24.2.15

  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    networks:
      sample:
        ipv4_address: 172.24.2.16

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    networks:
      sample:
        ipv4_address: 172.24.2.17

volumes:
  public-keys:

  prometheus:

  grafana:

  bootnode:
  validator1:
  validator2:
  validator3:
  validator4:
  rpcnode:
  node1:
  node2:

networks:
  sample:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.2.0/27
