---
version: '3.4'
services:

  orion1:
    image: "pegasyseng/orion:develop"
    environment:
      - ORION_OTHERNODES=http://orion2:8080/,http://orion3:8080/
      - ORION_NODEURL=http://orion1:8080
      - ORION_CLIENTURL=http://orion1:8888
    command: ["/config/orion.conf"]
    volumes:
      - ./config/orion/orion.conf:/config/orion.conf
      - ./config/orion/networkFiles/orion1:/keys/

  orion2:
    image: "pegasyseng/orion:develop"
    environment:
      - ORION_OTHERNODES=http://orion1:8080/,http://orion3:8080/
      - ORION_NODEURL=http://orion2:8080
      - ORION_CLIENTURL=http://orion2:8888
    command: ["/config/orion.conf"]
    volumes:
      - ./config/orion/orion.conf:/config/orion.conf
      - ./config/orion/networkFiles/orion2:/keys/

  orion3:
    image: "pegasyseng/orion:develop"
    environment:
      - ORION_OTHERNODES=http://orion2:8080/,http://orion1:8080/
      - ORION_NODEURL=http://orion3:8080
      - ORION_CLIENTURL=http://orion3:8888
    command: ["/config/orion.conf"]
    volumes:
      - ./config/orion/orion.conf:/config/orion.conf
      - ./config/orion/networkFiles/orion3:/keys/

  bootnode:
    build:
      context: besu/.
      args:
        BESU_VERSION: ${BESU_VERSION}
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    entrypoint: /opt/besu/bootnode_start.sh --config-file=/config/config.toml --network=dev --min-gas-price=0 --privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED}
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml

  rpcnode: #  We keep one node named rpcnode to have a specific node to connect the explorer
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: [
      "--config-file=/config/config.toml",
      "--network=dev",
      "--min-gas-price=0",
      "--rpc-http-api=EEA,WEB3,ETH,NET,PRIV",
      "--privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED}" ]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
    depends_on:
      - bootnode
    ports:
      - 8545:8545/tcp

  minernode:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: [
      "--config-file=/config/config.toml",
      "--network=dev",
      "--min-gas-price=0",
      "--miner-enabled=true",
      "--miner-coinbase=${MINER_COINBASE}",
      "--privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED}"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
    depends_on:
      - bootnode

  node1:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: [
      "--config-file=/config/config.toml",
      "--node-private-key-file=/opt/besu/keys/key",
      "--network=dev",
      "--min-gas-price=0",
      "--rpc-http-api=EEA,WEB3,ETH,NET,PRIV",
      "--privacy-enabled",
      "--privacy-url=http://orion1:8888",
      "--privacy-public-key-file=/config/orion/orion.pub",
      "--privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED}"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/orion/networkFiles/orion1/nodeKey.pub:/config/orion/orion.pub
      - ./config/besu/networkFiles/node1/keys:/opt/besu/keys
    depends_on:
      - bootnode
      - orion1
    ports:
      - 20000:8545/tcp
      - 20001:8546/tcp

  node2:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: [
      "--config-file=/config/config.toml",
      "--node-private-key-file=/opt/besu/keys/key",
      "--network=dev",
      "--min-gas-price=0",
      "--rpc-http-api=EEA,WEB3,ETH,NET,PRIV",
      "--privacy-enabled",
      "--privacy-url=http://orion2:8888",
      "--privacy-public-key-file=/config/orion/orion.pub",
      "--privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED}"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/orion/networkFiles/orion2/nodeKey.pub:/config/orion/orion.pub
      - ./config/besu/networkFiles/node2/keys:/opt/besu/keys
    depends_on:
      - bootnode
      - orion2
    ports:
      - 20002:8545/tcp
      - 20003:8546/tcp

  node3:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: [
      "--config-file=/config/config.toml",
      "--node-private-key-file=/opt/besu/keys/key",
      "--network=dev",
      "--min-gas-price=0",
      "--rpc-http-api=EEA,WEB3,ETH,NET,PRIV",
      "--privacy-enabled",
      "--privacy-url=http://orion3:8888",
      "--privacy-public-key-file=/config/orion/orion.pub",
      "--privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED}"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/orion/networkFiles/orion3/nodeKey.pub:/config/orion/orion.pub
      - ./config/besu/networkFiles/node3/keys:/opt/besu/keys
    depends_on:
      - bootnode
      - orion3
    ports:
      - 20004:8545/tcp
      - 20005:8546/tcp

  explorer:
    build: block-explorer-light/.
    image: sample-network/block-explorer-light:${BESU_VERSION}
    depends_on:
      - rpcnode
    ports:
      - 25000:80/tcp

  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp

volumes:
  public-keys:

  prometheus:

  grafana:
