# ensure name is set so that monitoring in Kibana is easy to identify
node.name: "logstash-${HOSTNAME}"

log.format: json
path:
  config: /usr/share/logstash/pipeline
  logs: /usr/share/logstash/logs

xpack:
  monitoring:
    enabled: true
    elasticsearch:
      hosts:  ${ES_HOST}